apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: cql-fhir-spark
  namespace: spark-operator
spec:
  type: Java
  mode: cluster
  image: "dhananjaypatkar/cql-fhir:v1"
  imagePullPolicy: Always
  mainClass: org.opencds.cqf.cql.spark.FHIRCQLEngineDriver
  mainApplicationFile: "local:///opt/spark/examples/cql-fhir-spark-1.0.jar"
  sparkVersion: "3.1.1"
  restartPolicy:
    type: Never
  volumes:
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.1.1
    serviceAccount: my-spark-release-spark-operator
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.1.1
    volumeMounts:
      - name: "test-volume"
        mountPath: "/tmp"